app:
  base-url: ${BASE_URL}
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:5173}
  rate-limit:
    create:
      capacity: ${RATE_LIMIT_CREATE_CAPACITY:10}
      refill-per-minute: ${RATE_LIMIT_CREATE_REFILL_PER_MINUTE:10}

server:
  port: 8080
  forward-headers-strategy: native
  tomcat:
    remoteip:
      remote-ip-header: X-Forwarded-For
      protocol-header: X-Forwarded-Proto

spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 40
      minimum-idle: 20
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
          jwk-set-uri: ${JWK_SET_URI}

  threads:
    virtual:
      enabled: true


management:
  endpoints:
    web:
      exposure:
        include: metrics,health,info

logging:
  level:
    org:
      hibernate:
        stat: DEBUG

supabase:
  project-url: ${PROJECT_URL}
  service-role-key: ${SUPABASE_SERVICE_ROLE_KEY}

maxmind:
  db-path: ${MAXMIND_DB_PATH}
  license-key: ${MAXMIND_LICENSE_KEY}
